#!/bin/sh

if [ $(id -u) = 0 ]; then
	printf "$(basename $0): do not run as root.\n"
	exit 1
fi

if [ $(id -u) != 0 ]; then
	if [ -f /usr/bin/sudo ]; then
		sudo=1
	fi
fi

this_dir=$(dirname $(realpath $0))
bin_path=/usr/bin
var_path=/var
src_file=$this_dir/$(basename $this_dir).sh
program_name=$(basename $this_dir)

#src_file=$this_dir/alpine.sh
#program_name="alpine"

if [ $(uname -o) != "GNU/Linux" ]; then
	bin_path=$PREFIX/bin
	var_path=$PREFIX/var
fi

if [ ! -f $src_file ]; then
    printf "$(basename $0): fail: $src_file: file not found\n"
    exit 1
else
    if [ ! -z $sudo ]; then
		sudo cp $src_file $bin_path/$program_name
		sudo chown 0 $bin_path/$program_name
		sudo chmod +x $bin_path/$program_name
		if [ ! -d $var_path/lib/$program_name ]; then
			sudo mkdir $var_path/lib/$program_name
		fi
	else 
		cp $src_file $bin_path/$program_name
		chmod +x $bin_path/$program_name
		if [ ! -d $var_path/lib/$program_name ]; then
			mkdir $var_path/lib/$program_name
		fi
	fi
	printf "install: done.\n"
	exit 1
fi