#!/bin/sh

PROGRAM=$(basename $0)
THIS=$(dirname $(realpath $0))
SOURCE=$THIS/src
BINDIR=/usr/bin

if [ $(uname -o) = "Android" ]; then
	if [ $(id -u) = 0 ]; then
        printf "$PROGRAM: must not be superuser to run command.\n"
		exit 1
	fi
	BINDIR=$PREFIX/bin
fi

FILEOUT=$THIS/box.sh

fwrite () {
	file_in=$(realpath $1)
	if [ -f $file_in ]; then
		cat $file_in >> $FILEOUT
		printf "\n\n" >> $FILEOUT
	fi
}

echo "#!/bin/sh" > $FILEOUT
echo "# $(date)" >> $FILEOUT
printf "\n" >> $FILEOUT

fwrite $SOURCE/init

for i in $SOURCE/function/*
do
	fwrite $i
done

fwrite $SOURCE/main

chmod +x $FILEOUT

if [ $(id -u) != 0 ]; then
	sudo cp $FILEOUT $BINDIR/box
else
	cp $FILEOUT $BINDIR/box
fi